target("chapter0_ref_tests")
    set_kind("binary")
    set_languages("c++23")
    add_files("chapter0_tests.cpp", "../test_metaInfo.cpp", "../../src/chapter0/global.cppm", "../../src/chapter0/metaInfo/metaInfo.cppm")
    add_deps("chapter0_modules")
    add_includedirs("..", "../../src")
    add_packages("gtest")

target("chapter0_tests")
    set_kind("binary")
    set_languages("c++23")
    add_files("chapter0_tests.cpp", "../test_metaInfo.cpp", "../../mystl/chapter0/global.cppm", "../../mystl/chapter0/metaInfo/metaInfo.cppm")
    add_deps("chapter0_modules")
    add_includedirs("..", "../../mystl")
    add_packages("gtest")